# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CheshireCat's Website
email: lmaomaoz@gmail.com
description: > #site description.
baseurl: "/blog" 
url: "http://lmaomaoz.com"
twitter_username: CheshireCat
github_username:  CheshireJCat

# Build settings
markdown: kramdown
port: 5001
